# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-12 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=64, verbose_name='\u6635\u79f0')),
                ('user', models.CharField(max_length=64, verbose_name='\u7528\u6237')),
                ('passwd', models.CharField(max_length=64, verbose_name='\u5bc6\u7801')),
                ('email', models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1')),
                ('sex', models.BooleanField(choices=[(1, '\u7537'), (0, '\u5973')], default=1, verbose_name='\u6027\u522b')),
                ('cdate', models.DateTimeField(auto_now_add=True, verbose_name='\u6ce8\u518c\u65e5\u671f')),
                ('ll_date', models.DateTimeField(auto_now=True, verbose_name='\u672b\u6b21\u767b\u5f55\u65f6\u95f4')),
            ],
        ),
    ]
