# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-12 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env_name', models.CharField(max_length=128, verbose_name='\u73af\u5883\u540d')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='\u63cf\u8ff0')),
            ],
        ),
        migrations.CreateModel(
            name='Os',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_name', models.CharField(max_length=128, verbose_name='\u64cd\u4f5c\u7cfb\u7edf')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='\u63cf\u8ff0')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_status', models.IntegerField(choices=[(0, '\u6b63\u5728\u5ba1\u6838'), (1, '\u5df2\u901a\u8fc7'), (2, '\u672a\u901a\u8fc7')], verbose_name='\u5ba1\u6838\u72b6\u6001')),
                ('unit', models.CharField(max_length=128, verbose_name='\u9879\u76eeID')),
                ('project_name', models.CharField(max_length=128, verbose_name='\u9879\u76ee\u540d')),
                ('git', models.CharField(blank=True, max_length=512, verbose_name='GIT\u4ed3\u5e93')),
                ('cdate', models.DateTimeField(auto_now_add=True, verbose_name='\u7533\u8bf7\u65f6\u95f4')),
                ('remark', models.CharField(blank=True, max_length=256, verbose_name='\u5907\u6ce8')),
                ('architect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_architect', to='account.User', verbose_name='\u67b6\u6784\u5e08')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_developer', to='account.User', verbose_name='\u5f00\u53d1')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_manager', to='account.User', verbose_name='\u9879\u76ee\u7ecf\u7406')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_status', models.IntegerField(choices=[(0, '\u6b63\u5728\u5ba1\u6838'), (1, '\u5df2\u901a\u8fc7'), (2, '\u672a\u901a\u8fc7')], verbose_name='\u5ba1\u6838\u72b6\u6001')),
                ('purpose', models.CharField(max_length=128, verbose_name='\u7528\u9014')),
                ('cpu', models.IntegerField(choices=[(2, '2\u6838'), (4, '4\u6838'), (8, '8\u6838'), (16, '16\u6838'), (32, '32\u6838'), (64, '64\u6838')], verbose_name='CPU')),
                ('mem', models.IntegerField(choices=[(2, '2G'), (4, '4G'), (8, '8G'), (16, '16G'), (32, '32G'), (64, '64G'), (128, '128G')], verbose_name='\u5185\u5b58')),
                ('disk', models.IntegerField(choices=[(200, '200G'), (500, '500G'), (1000, '1T'), (2000, '2T'), (4000, '4T'), (8000, '8T'), (16000, '16T')], verbose_name='\u78c1\u76d8')),
                ('number', models.IntegerField(verbose_name='\u7533\u8bf7\u53f0\u6570')),
                ('cdate', models.DateTimeField(auto_now_add=True, verbose_name='\u7533\u8bf7\u65f6\u95f4')),
                ('apply_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User', verbose_name='\u7533\u8bf7\u4eba')),
                ('environ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='op.Environ', verbose_name='\u6240\u5c5e\u73af\u5883')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='op.Os', verbose_name='\u64cd\u4f5c\u7cfb\u7edf')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='op.Project', verbose_name='\u9879\u76eeID')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='\u670d\u52a1\u5668IP')),
                ('state', models.IntegerField(choices=[(0, '\u7a7a\u95f2'), (1, '\u4f7f\u7528\u4e2d'), (2, '\u5df2\u521d\u59cb\u5316'), (3, '\u5df2\u4e0b\u7ebf'), (4, '\u5df2\u56de\u6536')], default=0, verbose_name='\u72b6\u6001')),
                ('user', models.IntegerField(choices=[(0, 'root'), (1, 'developer'), (2, 'test')], default=0, verbose_name='\u5e10\u53f7')),
                ('port', models.IntegerField(choices=[(0, 22), (1, 21312), (2, 21212), (3, 53977)], default=0, verbose_name='\u7aef\u53e3')),
                ('remark', models.CharField(blank=True, max_length=256, verbose_name='\u5907\u6ce8')),
                ('cdate', models.DateTimeField(auto_now_add=True, verbose_name='\u7533\u8bf7\u65f6\u95f4')),
                ('environ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='op.Environ', verbose_name='\u6240\u5c5e\u73af\u5883')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='op.Os', verbose_name='\u64cd\u4f5c\u7cfb\u7edf')),
            ],
        ),
        migrations.CreateModel(
            name='Vhost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='\u670d\u52a1\u5668IP')),
                ('state', models.IntegerField(choices=[(0, '\u7a7a\u95f2'), (1, '\u4f7f\u7528\u4e2d'), (2, '\u5df2\u521d\u59cb\u5316'), (3, '\u5df2\u4e0b\u7ebf'), (4, '\u5df2\u56de\u6536')], default=0, verbose_name='\u72b6\u6001')),
                ('user', models.IntegerField(choices=[(0, 'root'), (1, 'developer'), (2, 'test')], default=0, verbose_name='\u5e10\u53f7')),
                ('port', models.IntegerField(choices=[(0, 22), (1, 21312), (2, 21212), (3, 53977)], default=0, verbose_name='\u7aef\u53e3')),
                ('remark', models.CharField(blank=True, max_length=256, verbose_name='\u5907\u6ce8')),
                ('cdate', models.DateTimeField(auto_now_add=True, verbose_name='\u7533\u8bf7\u65f6\u95f4')),
                ('environ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='op.Environ', verbose_name='\u6240\u5c5e\u73af\u5883')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='op.Os', verbose_name='\u64cd\u4f5c\u7cfb\u7edf')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='op.Server', verbose_name='\u6240\u5c5e\u7269\u7406\u673a')),
            ],
        ),
    ]
