# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('op', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='proj_applyer', to='account.User', verbose_name='\u7533\u8bf7\u4eba'),
        ),
        migrations.AlterField(
            model_name='project',
            name='auth_status',
            field=models.IntegerField(choices=[(0, '\u5f85\u5ba1\u6838'), (1, '\u5df2\u901a\u8fc7'), (2, '\u672a\u901a\u8fc7')], default=0, verbose_name='\u5ba1\u6838\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='auth_status',
            field=models.IntegerField(choices=[(0, '\u5f85\u5ba1\u6838'), (1, '\u5df2\u901a\u8fc7'), (2, '\u672a\u901a\u8fc7')], default=0, verbose_name='\u5ba1\u6838\u72b6\u6001'),
        ),
    ]
