# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('op', '0002_auto_20161116_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proj_applyer', to='account.User', verbose_name='\u7533\u8bf7\u4eba'),
        ),
    ]
