# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op', '0004_auto_20161116_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='auth_status',
            field=models.IntegerField(choices=[(0, '\u5f85\u5ba1\u6279'), (1, '\u901a\u8fc7'), (2, '\u672a\u901a\u8fc7')], default=0, verbose_name='\u5ba1\u6279\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='auth_status',
            field=models.IntegerField(choices=[(0, '\u5f85\u5ba1\u6279'), (1, '\u901a\u8fc7'), (2, '\u672a\u901a\u8fc7')], default=0, verbose_name='\u5ba1\u6279\u72b6\u6001'),
        ),
    ]
