# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op', '0005_auto_20161116_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='number',
            field=models.IntegerField(choices=[(1, '1\u53f0'), (2, '2\u53f0'), (3, '3\u53f0'), (4, '4\u53f0'), (5, '5\u53f0'), (6, '7\u53f0'), (8, '8\u53f0'), (9, '9\u53f0'), (10, '10\u53f0')], verbose_name='\u7533\u8bf7\u53f0\u6570'),
        ),
    ]
