# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('op', '0009_auto_20161116_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='superviser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_rsuperviser', to='account.User', verbose_name='\u5ba1\u6838\u4eba'),
        ),
    ]
