# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op', '0010_auto_20161116_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='cpu',
            field=models.IntegerField(choices=[(2, '2\u6838'), (4, '4\u6838'), (8, '8\u6838'), (16, '16\u6838'), (32, '32\u6838'), (64, '64\u6838')], default=2, verbose_name='CPU'),
        ),
        migrations.AddField(
            model_name='server',
            name='disk',
            field=models.IntegerField(choices=[(200, '200G'), (500, '500G'), (1000, '1T'), (2000, '2T'), (4000, '4T'), (8000, '8T'), (16000, '16T')], default=200, verbose_name='\u78c1\u76d8'),
        ),
        migrations.AddField(
            model_name='server',
            name='mem',
            field=models.IntegerField(choices=[(2, '2G'), (4, '4G'), (8, '8G'), (16, '16G'), (32, '32G'), (64, '64G'), (128, '128G')], default=2, verbose_name='\u5185\u5b58'),
        ),
        migrations.AddField(
            model_name='vhost',
            name='cpu',
            field=models.IntegerField(choices=[(2, '2\u6838'), (4, '4\u6838'), (8, '8\u6838'), (16, '16\u6838'), (32, '32\u6838'), (64, '64\u6838')], default=2, verbose_name='CPU'),
        ),
        migrations.AddField(
            model_name='vhost',
            name='disk',
            field=models.IntegerField(choices=[(200, '200G'), (500, '500G'), (1000, '1T'), (2000, '2T'), (4000, '4T'), (8000, '8T'), (16000, '16T')], default=200, verbose_name='\u78c1\u76d8'),
        ),
        migrations.AddField(
            model_name='vhost',
            name='mem',
            field=models.IntegerField(choices=[(2, '2G'), (4, '4G'), (8, '8G'), (16, '16G'), (32, '32G'), (64, '64G'), (128, '128G')], default=2, verbose_name='\u5185\u5b58'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='cpu',
            field=models.IntegerField(choices=[(2, '2\u6838'), (4, '4\u6838'), (8, '8\u6838'), (16, '16\u6838'), (32, '32\u6838'), (64, '64\u6838')], default=2, verbose_name='CPU'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='disk',
            field=models.IntegerField(choices=[(200, '200G'), (500, '500G'), (1000, '1T'), (2000, '2T'), (4000, '4T'), (8000, '8T'), (16000, '16T')], default=200, verbose_name='\u78c1\u76d8'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='mem',
            field=models.IntegerField(choices=[(2, '2G'), (4, '4G'), (8, '8G'), (16, '16G'), (32, '32G'), (64, '64G'), (128, '128G')], default=2, verbose_name='\u5185\u5b58'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='purpose',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u7528\u9014'),
        ),
    ]
